name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo docker-compose -f docker-compose-local.yml up --build
      working-directory: book-library/  # Specify the path to your code

